export const useSchedule = () => {
    
    return {
    cinemaDetails: [
      {  
        title: "Doctor Strange in the Multiverse of Madness",
        movieId : "movie1",
        location: "SM North Edsa",
        cinemaPosterURL: 'smcinema.png',
        cinemaNum: 1,
        timeSlot: ["09:00", "11:00", "13:00", "15:00", "18:00"],
      },
      {  
        title: "Everything Everywhere All at Once",
        movieId : "movie5",
        location: "SM Cubao",
        cinemaPosterURL: 'smcinema.png',
        cinemaNum: 2,
        timeSlot: ["09:00", "11:00", "13:00", "15:00", "18:00"],
      },
      {  
        title: "Doctor Strange in the Multiverse of Madness",
        movieId : "movie1",
        location: "SM Aura",
        cinemaPosterURL: 'smcinema.png',
        cinemaNum: 1,
        timeSlot: ["09:00", "11:00", "13:00", "15:00", "18:00", "20:00"],
      },
      {  
        title: "Doctor Strange in the Multiverse of Madness",
        movieId : "movie1",
        location: "SM Light Mandaluyong",
        cinemaPosterURL: 'smcinema.png',
        cinemaNum: 1,
        timeSlot: ["09:00", "11:00", "13:00", "15:00", "18:00"],
      },
      {  
        title: "Everything Everywhere All at Once",
        movieId : "movie2",
        location: "SM North Edsa",
        cinemaPosterURL: 'smcinema.png',
        cinemaNum: 2,
        timeSlot: ["09:00", "11:00", "13:00", "15:00", "18:00", "20:00"],
      },
      {  
        title: "The Bad Guys",
        movieId : "movie2",
        location: "SM North Edsa",
        cinemaPosterURL: 'smcinema.png',
        cinemaNum: 4,
        timeSlot: ["09:00", "11:00", "13:00", "15:00"],
      },
      {  
        title: "Doctor Strange in the Multiverse of Madness",
        movieId : "movie1",
        location: "SM Pasig",
        cinemaPosterURL: 'smcinema.png',
        cinemaNum: 4,
        timeSlot: ["09:00", "11:00", "13:00", "15:00", "18:00"],
      },
      {  
        title: "Everything Everywhere All at Once",
        movieId : "movie5",
        location: "SM Cubao",
        cinemaPosterURL: 'smcinema.png',
        cinemaNum: 1,
        timeSlot: ["09:00", "11:00", "13:00", "15:00", "18:00", "20:00"],
      },
      {  
        title: "Doctor Strange in the Multiverse of Madness",
        movieId : "movie1",
        location: "SM Aura",
        cinemaPosterURL: 'smcinema.png',
        cinemaNum: 3,
        timeSlot: ["09:00", "11:00", "13:00", "15:00", "18:00", "20:00"],
      },
      {  
        title: "Firestarter",
        movieId : "movie1",
        location: "SM Light Mandaluyong",
        cinemaPosterURL: 'smcinema.png',
        cinemaNum: 4,
        timeSlot: ["09:00", "11:00", "13:00", "15:00", "18:00"],
      },
      {  
        title: "Firestarter",
        movieId : "movie2",
        location: "SM Cubao",
        cinemaPosterURL: 'smcinema.png',
        cinemaNum: 1,
        timeSlot: ["09:00", "11:00", "13:00", "15:00", "18:00", "20:00"],
      },
      {  
        title: "The Bad Guys",
        movieId : "movie2",
        location: "SM Laguna",
        cinemaPosterURL: 'smcinema.png',
        cinemaNum: 4,
        timeSlot: ["09:00", "11:00", "13:00", "15:00"],
      },
      {  
        title: "Doctor Strange in the Multiverse of Madness",
        movieId : "movie1",
        location: "SM Light Mandaluyong",
        cinemaPosterURL: 'smcinema.png',
        cinemaNum: 1,
        timeSlot: ["09:00", "11:00", "13:00", "15:00", "18:00"],
      },
      {  
        title: "Everything Everywhere All at Once",
        movieId : "movie2",
        location: "SM North Edsa",
        cinemaPosterURL: 'smcinema.png',
        cinemaNum: 2,
        timeSlot: ["09:00", "11:00", "13:00", "15:00", "18:00", "20:00"],
      },
      {  
        title: "The Bad Guys",
        movieId : "movie2",
        location: "SM North Edsa",
        cinemaPosterURL: 'smcinema.png',
        cinemaNum: 4,
        timeSlot: ["09:00", "11:00", "13:00", "15:00"],
      },
      {  
        title: "Sonic the HedgeHog 2",
        movieId : "movie1",
        location: "SM Pasig",
        cinemaPosterURL: 'smcinema.png',
        cinemaNum: 3,
        timeSlot: ["09:00", "11:00", "13:00", "15:00", "18:00"],
      },
      {  
        title: "Sonic the HedgeHog 2",
        movieId : "movie5",
        location: "SM Cubao",
        cinemaPosterURL: 'smcinema.png',
        cinemaNum: 3,
        timeSlot: ["09:00", "11:00", "13:00", "15:00", "18:00", "20:00"],
      },
      {  
        title: "Sonic the HedgeHog 2",
        movieId : "movie1",
        location: "SM Aura",
        cinemaPosterURL: 'smcinema.png',
        cinemaNum: 1,
        timeSlot: ["09:00", "11:00", "13:00", "15:00", "18:00", "20:00"],
      },
      {  
        title: "Firestarter",
        movieId : "movie1",
        location: "SM Light Mandaluyong",
        cinemaPosterURL: 'smcinema.png',
        cinemaNum: 1,
        timeSlot: ["09:00", "11:00", "13:00", "15:00", "18:00"],
      },
      {  
        title: "Firestarter",
        movieId : "movie2",
        location: "SM Cubao",
        cinemaPosterURL: 'smcinema.png',
        cinemaNum: 2,
        timeSlot: ["09:00", "11:00", "13:00", "15:00", "18:00", "20:00"],
      },
      {  
        title: "The Bad Guys",
        movieId : "movie2",
        location: "SM Laguna",
        cinemaPosterURL: 'smcinema.png',
        cinemaNum: 2,
        timeSlot: ["09:00", "11:00", "13:00", "15:00"],
      },

    ]}
}